// Custom hooks exports
export * from './useNavigation';
export * from './useCategories';
export * from './useProducts';
export * from './useProductDetail';
export * from './useOnlineStatus';
export * from './useOptimisticUpdates';
export * from './useErrorRecovery';
export * from './useGlobalLoading';
export * from './useCacheManager';
export * from './useTouchGestures';