name = "datashelf-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "datashelf-api-dev"
vars = { ENVIRONMENT = "development" }

[env.staging]
name = "datashelf-api-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "datashelf-api"
vars = { ENVIRONMENT = "production", CORS_ORIGINS = "https://datashelf.pages.dev" }

# Environment variables (set via wrangler secret put or GitHub Actions)
# SUPABASE_URL
# SUPABASE_ANON_KEY
# SCRAPER_API_KEY
# SCRAPER_SERVICE_URL

# Using Workers Cache API (caches.default) - no KV namespace needed

# Custom domains (configure after deployment)
# [env.production.routes]
# pattern = "api.datashelf.com/*"
# zone_name = "datashelf.com"

# Rate limiting and resource limits (CPU limits not available on free plan)
# [limits]
# cpu_ms = 100

# Build configuration
# [build]
# command = "npm run build"

# Deployment triggers
[triggers]
crons = []