name = "datashelf-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "datashelf-api-dev"
vars = { 
  ENVIRONMENT = "development",
  CORS_ORIGINS = "http://localhost:3000,http://localhost:5173"
}

[env.staging]
name = "datashelf-api-staging"
vars = { 
  ENVIRONMENT = "staging",
  CORS_ORIGINS = "https://datashelf-staging.pages.dev,http://localhost:3000,http://localhost:5173"
}

[env.production]
name = "datashelf-api"
vars = { 
  ENVIRONMENT = "production",
  CORS_ORIGINS = "https://datashelf.pages.dev,https://datashelf.com,https://www.datashelf.com,http://localhost:3000,http://localhost:5173"
}

# Environment variables (set via wrangler secret put or GitHub Actions)
# SUPABASE_URL
# SUPABASE_ANON_KEY
# SCRAPER_API_KEY
# SCRAPER_SERVICE_URL

# Using Workers Cache API (caches.default) - no KV namespace needed

# Custom domains (configure after deployment)
# [env.production.routes]
# pattern = "api.datashelf.com/*"
# zone_name = "datashelf.com"

# Rate limiting and resource limits (CPU limits not available on free plan)
# [limits]
# cpu_ms = 100

# Build configuration
# [build]
# command = "npm run build"

# Deployment triggers
[triggers]
crons = []